/* Generated By:JavaCC: Do not edit this line. SLParserConstants.java */
package jade.content.lang.sl;

public interface SLParserConstants {

  int EOF = 0;
  int LBRACE = 5;
  int RBRACE = 6;
  int VARIABLE = 7;
  int INTEGER = 8;
  int HEXINTEGER = 9;
  int FLOATONE = 10;
  int FLOATTWO = 11;
  int WORD = 12;
  int STRING_LITERAL = 13;
  int PARAMETERNAME = 14;
  int PARAMETERNAME_STRING = 15;
  int DATETIME = 16;
  int PREFIXBYTELENGTHENCODEDSTRING = 17;
  int METASYMBOL = 18;
  int LBRACE2 = 23;
  int RBRACE2 = 24;
  int ACTION = 25;
  int REFERENTIALOP = 26;
  int MODALOP = 27;
  int ARITHMETICOP = 28;
  int ACTIONOP = 29;
  int ACTIONOPLL = 30;
  int UNARYLOGICALOP = 31;
  int BINARYLOGICALOP = 32;
  int QUANTIFIER = 33;
  int WORD2 = 34;
  int STRING_LITERAL2 = 35;
  int METASYMBOL2 = 36;

  int DEFAULT = 0;
  int OPERATORSTATE = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "<VARIABLE>",
    "<INTEGER>",
    "<HEXINTEGER>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<WORD>",
    "<STRING_LITERAL>",
    "<PARAMETERNAME>",
    "<PARAMETERNAME_STRING>",
    "<DATETIME>",
    "<PREFIXBYTELENGTHENCODEDSTRING>",
    "<METASYMBOL>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"action\"",
    "<REFERENTIALOP>",
    "<MODALOP>",
    "<ARITHMETICOP>",
    "<ACTIONOP>",
    "<ACTIONOPLL>",
    "\"not\"",
    "<BINARYLOGICALOP>",
    "<QUANTIFIER>",
    "<WORD2>",
    "<STRING_LITERAL2>",
    "<METASYMBOL2>",
  };

}
